fns:
  - &server_fn |
      def handle_event(context):
        log("hello server")

  - &client_fn |
      def handle_event(context):
        log("hello client")

graph_defn:
  name: "test graph"
  nodes:
    - name: server
      fn: *server_fn
      attrs:
        tick: 5s
        color: [1., 0., 1., 1.]
    - name: client1
      fn: *client_fn
      attrs:
        ticks: 10s
        color: [1., 1., 0., 0.]
    - name: client2
      fn: *client_fn
  allowed_connections:
    server: [client1, client2]
  graph:
    server: [client1, client2]
  graph_attrs:
      title: "A Sample Graph!"
      background: [0.1, 0.1, 0.1, 1.]
      connection_color: [0., 0.9, 0.9, 1.]
      text_color: [0.5, 0.5, 0.5, 1.0]
