/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_compileresult_free: (a: number, b: number) => void;
export const compile_code: (a: number, b: number) => number;
export const compile_code_with_sources: (a: number, b: number, c: number, d: number) => number;
export const compileresult_error_log: (a: number) => [number, number];
export const compileresult_result: (a: number) => number;
export const get_code_schema: () => [number, number];
export const get_import_urls: (a: number, b: number) => [number, number];
export const main: (a: number, b: number) => number;
export const wgpu_render_bundle_set_pipeline: (a: number, b: bigint) => void;
export const wgpu_render_bundle_draw_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_set_bind_group: (a: number, b: number, c: bigint, d: number, e: number) => void;
export const wgpu_render_bundle_set_vertex_buffer: (a: number, b: number, c: bigint, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_set_push_constants: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_draw: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wgpu_render_bundle_insert_debug_marker: (a: number, b: number) => void;
export const wgpu_render_bundle_pop_debug_group: (a: number) => void;
export const wgpu_render_bundle_set_index_buffer: (a: number, b: bigint, c: number, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_push_debug_group: (a: number, b: number) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___js_sys_ea71831a44c3662a___Array__web_sys_b6b4da6eec6572d0___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue__core_ed718c3d60ebd546___result__Result_____wasm_bindgen_5cfc456e5c09313a___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue______true__11: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue______true__12: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue______true__13: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue______true__14: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue______true__15: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___wasm_bindgen_5cfc456e5c09313a___JsValue______true__16: (a: number, b: number, c: any) => void;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke___bool__true_: (a: number, b: number) => number;
export const wasm_bindgen_5cfc456e5c09313a___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
